name: Bit build and test CI

on:
  pull_request:
    branches: [main]

jobs:
  bit-build-and-test:
    runs-on: ubuntu-latest
    env:
      BIT_TOKEN: ${{ secrets.BIT_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.32.2
          run_install: false
      - name: Install packages
        run: pnpm i 
      - name: Build
        run: pnpm run build
      - name: Test
        run: pnpm run test
