name: Bit build and test CI

on:
  pull_request:
    branches: [main]

jobs:
  bit-build-and-test:
    runs-on: ubuntu-latest
    env:
      BIT_TOKEN: ${{ secrets.BIT_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.32.2
          run_install: true

      - name: Install bit-bin
        run: pnpm install bit-bin@14.7.6 -g
      - name: Bit build & Bit test
        run: |
          bit config set analytics_reporting false
          bit config set anonymous_reporting false
          bit config set user.token $BIT_TOKEN
          bit config 
          bit -v && bit import
          bit status
          bit test